### ISSUE TITLE
Set-up CircleCI for the project

### ISSUE THREAD

**Issue by epochyx** [drftpd-ng/drftpd#101]
We should setup CircleCI so we can test the code automatically.
Those are the goals before releasing 4.0:
- [ ] Set up a way to automatically build the code
- [ ] Set up travis CI to build on java 14 / linux
- [ ] Fix the very few available unit tests
- [ ] Set up a simple scenario to start a dummy master
- [ ] Set up a simple functional test to check that it works

Next:
- [ ] Build and start/add a slave
- [ ] Validate the slave status
- [ ] Add unit tests for major classes
- [ ] Add feature tests

**Comment by zc0nf** [comment]
Done
