### ISSUE TITLE
Nukefilter setting

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#130]
**Describe the bug**
When using nukefilter.conf, nothing happens.

this config is set:
global.filter.regex=(?i)^.+(SUBBED|DUBBED|TESTPRE|TEST.PRE|DONT.RACE).+$

The regexp works on a online regexp checker.
On MKD f.ex testing.DUBBED.x264-tests there is no nuke announce after a while.
Either i have forgot to config somewhere else, or it do not like it.
There is no error logs .

**DrFTPd**
 - OS: Debian
 - Java version 14
 - drftpd version v4

**Comment by k-2-r** [comment]
Just try it without any problem. Do you try to change the config after drftpd start? For now SITE RELOAD doesnt refresh the plugins configuration.

**Comment by k-2-r** [comment]
Just push the come back of SITE RELOAD for plugins configuration. https://github.com/drftpd-ng/drftpd/compare/050a9382a682...b3a83102d487
