### ISSUE TITLE
Create a zipped master and slave configuration

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#134]
Hello,

Is it possible to implement the automatic creation of a master.zip and slave.zip once the mvn install is finished? or added an option to do so?

Thank you

**Comment by hrxcodes** [comment]
I think this is not necessary.

* Linux: `cd runtime; tar -cf slave.tar slave`
* Windows you can just right-click on the folder -> Send to -> Compressed zip

That should be easy/god enough, especially since you need to include/copy the key for SSL anyways
