### ISSUE TITLE
Feature: IRC flood protection

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#145]
On non-private IRC networks there are flood limitations.
If those could be set in the IRC plugin to avoid having the bot quit due to flood that would be handy 

`has quit (Excess Flood)`

1. Login to a IRC net like linknet/efnet
2. site invite yourself
3. Issue `!help` in a channel where the sitebot is

**Expected behavior**
Bot not being kicked from the IRC net since it's aware of the flood rate-limits

**Comment by zc0nf** [comment]
in irc.conf

```
# Sets the time in milliseconds we wait after each message is sent.
# The best protection you can set to avoid flood disconnects.
# Default: [300]
message.sendDelay=300
```
