### ISSUE TITLE
TOP TRIAL ERROR.

### ISSUE THREAD

**Issue by HardFox1** [drftpd-ng/drftpd#157]
Hello i have problem whith toptrial.
I have configure toptrial 
This is mine .conf

https://0bin.net/paste/QvTjqDa1shxPrgmr#LfZtGRQ96NLBsnpZfovOye83cEq5toKlYPzsw2vb0nD

But i have this error 
[ TRIAL EDEN - 0 Racers - Top 40 Will Stay - (4 Days Remaining) (Min 50.0GB) and 30% of #1 monthup) ]

Not read user for trial configuration.
This is error in master.log

```
ERROR 2020-05-27T17:13:37,419 [Master Main Thread] org.drftpd.master.commands.config.hooks.DefaultConfigHandler [] - Unable to read <filename> directive ignored
ERROR 2020-05-27T17:18:27,795 [SiteBot Command Handler-91 - Waiting for commands] org.drftpd.master.commands.config.hooks.DefaultConfigHandler [] - Unable to read <filename> directive ignored
ERROR 2020-05-27T17:19:32,099 [SiteBot Command Handler-101 - Waiting for commands] org.drftpd.master.commands.config.hooks.DefaultConfigHandler [] - Unable to read <filename> directive ignored
ERROR 2020-05-27T17:21:33,114 [SiteBot Command Handler-91 - Waiting for commands] org.drftpd.master.commands.config.hooks.DefaultConfigHandler [] - Unable to read <filename> directive ignored
```

Not have another error.
Please, help me to configure it? 
Thanks for the help and pacience. 
Best regards.

Mine configuretion in perm.conf is 
```
# Control credit ratio on uploads (0 = no credits)
#creditcheck <path> <ratio> <=group/-user>

# Control credit ratio on downloads (0 = no credits)
#creditloss <path> <ratio> <=group/-user>

# Limit UL/DL over time
# direction : UP / DN
# period : ALL / DAY / WEEK / MONTH
#creditlimit <path> <direction> <period> <bytes> <=group/-user>
```

If I change this , please send me one good configuration.
Thanks a lot.

**Comment by hrxcodes** [comment]
Hi, this is likely just a configuration issue on your end.
`trial.conf` would be needed too for checking what is wrong, but I guess that might be on the expired 0bin link.

I will close this issue since it's rather old. If this is still a issue in a clean dr4.0, then post `trial.conf` and `perms.conf` that could be used to replicate the issue and we will reopen the issue.
