### ISSUE TITLE
Speedtest.conf issues

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#160]
When using speedtest.conf the files is not updating , i.e they not show up in speedtest folder.
It might be thought to be this way, but maybe documentation needs that it does so?.
This was fixed by disable it by un comment.

**Comment by mvangoor** [comment]
Could you please add the parts in the configuration you changed?

**Comment by snabben** [comment]
#path.1=/speedtest/slave
#path.2=/speedtest/slave2
#path.3=/speedtest/slave3
#path.4=/speedtest/slave4
#path.5=/speedtest/slave5

**Comment by mvangoor** [comment]
Checking SpeedTestPostHook.java the file is always deleted if it matches a speedtest directory.
It will only announce speedtest to irc if it is a speedtest directory.

So based on that it is working 'as designed'.

Is there an improvement you are aiming for here?

**Comment by snabben** [comment]
Not really, more an clarification in the .conf that it behaves like this   ( not updating files ) when using this conf.
