### ISSUE TITLE
Archive issue

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#161]
If choosing multiple folders, and sending an manual archive command, result in a good confirmation in status window of ftprush, but it only start to archive 1 of all dirs.

In drftpd 3.0 it worked flawless to multi archive using this command:
site archive %f MoveReleaseToSpecificSlaves numofslaves=1 slavename.1=%d[Slavename:]
This will give you a popup box so you can enter the slavename.
Even if i choose 1 dir, send comand, then choose next dir and send command, it do not add more jobs to queue even if it say so.

```
22:34:48) [2] site archive Rel1 MoveReleaseToSpecificSlaves numofslaves=1 slavename.1=A1
22:34:48) [2] 200- Started ArchiveHandler for MoveReleaseToSpecificSlaves on /legit/iso/Rel1
22:34:48) [2] 200 Command okay
22:34:48) [2] site archive Rel2 MoveReleaseToSpecificSlaves numofslaves=1 slavename.1=A1
22:34:48) [2] 200- Started ArchiveHandler for MoveReleaseToSpecificSlaves on /legit/iso/Rel2
22:34:48) [2] 200 Command okay
22:34:48) [2] site archive Rel3 MoveReleaseToSpecificSlaves numofslaves=1 slavename.1=A1
22:34:48) [2] 200- Started ArchiveHandler for MoveReleaseToSpecificSlaves on /legit/iso/Rel3
22:34:48) [2] 200 Command okay
22:34:50) [2] site listjobs
22:34:51) [2] 200- Total # of jobs is 1
22:34:51) [2] 200 Command okay
```

**Comment by mvangoor** [comment]
The commit resolves the observed behaviour, but does allow for 1000+ jobs to be pending. A better solution is a threadpool with a pending archive queue. Also a way to empty the queue if we need to stop.

**Comment by mvangoor** [comment]
Archive system has been rewritten and this should work out of the box now
