### ISSUE TITLE
Slaveselection should reload when adding a new slave

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#165]
**Describe the bug**
Using assume.remove in slaveselection does not exclude a new slave being added `site addslave`

**To Reproduce**
1. Set slaveselection to send to Slave1 with assume remove being true
2. site load
3. site addslave Slave2 + addmask
4. Upload files
5. Files are sent to Slave1 & Slave2

**Expected behavior**
Files should not be sent to Slave2

**Comment by mvangoor** [comment]
We should add this to 'doSITE_ADDSLAVE'
`GlobalContext.getGlobalContext().getSlaveSelectionManager().reload();`

**Comment by zc0nf** [comment]
From @mvangoor :
We should add this to 'doSITE_DELSLAVE'
GlobalContext.getGlobalContext().getSlaveSelectionManager().reload();

**Comment by mvangoor** [comment]
But adding that to delslave will crash the master if the slave is still being mentioned in the configs. The solution for that is to add prehooks to delslave for every location that uses slaves in the config. This way plugins who also reference slaves can be fixed

**Comment by mvangoor** [comment]
This should now be fixed. If not please re-open
