### ISSUE TITLE
VFS timestamp is not updated on pre

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#169]
**Describe the bug**
On pre release it's removed by autofreespace if it's too old

**To Reproduce**
1. Setup autofreepsace, exclude pre dir
2. Upload a release to pre folder
3. Ingest enough data so that atuofreespace triggers due to out of space
4. A little while after site pre `release` it's cleaned by autofreespace cause it's the oldest item

**Expected behavior**
Update timestamp on the release when issuing `site pre`

**Comment by zc0nf** [comment]
@hrxcodes can you past conf files?

**Comment by hrxcodes** [comment]
Make sure you use sectionmanager and the section is defined.

## autofreespace.conf
```
cycleTime=3
keepFree=100GB
announce.only=false
delete.on.date=false
delete.on.space=true
1.section=TV
```

**Comment by zc0nf** [comment]
After several tests, I cannot reproduce the problem on version 4.x, each directory in the pre folder has its timestamp which changes once the pre command is executed

**Comment by hrxcodes** [comment]
Then this seems fixed or at least not reproducible in dr4.
Closing

**Comment by mvangoor** [comment]
@hrxcodes hit this issue again and was able to answer a few questions.
This led to the discovery of the fact that on pre the directory creation time is not reset and the autofreespace plugin checks on creation time.
