### ISSUE TITLE
site user (name) output is showing some '[unknown]' and non-existent class references

### ISSUE THREAD

**Issue by mvangoor** [drftpd-ng/drftpd#172]
Weekly Allotment: ${org.drftpd.master.commands.usermanagement.UserManagement@wkly_allotment}
Times nuked: [Unknown]
Bytes nuked: [Unknown]
Requests: [Unknown]
Filled requests: [Unknown]
Requests this week: [Unknown]
Banned Until: ${org.drftpd.master.commands.usermanagement.UserManagement@ban_time}

**Comment by zc0nf** [comment]
Fixed
