### ISSUE TITLE
mirror.conf problems

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#180]
When serting up mirror.conf, and it shall mirror a dir to two slaves fex, but then you issue a site pre command, then it seems to leave the dir it started mirroring, in the folder, 
for me it was incomplete  as it hadnt have time to mirror all files in the pre/dir/dir,
Maybe it should stop the mirror work, if dir is moved?

**Comment by mvangoor** [comment]
Please test this and let us know if it works @snabben

**Comment by zc0nf** [comment]
Up! @snabben

**Comment by snabben** [comment]
Hello Friends! I have no install to test anymore. I can do some tests later.

**Comment by mvangoor** [comment]
Appreciate the attention here

**Comment by mvangoor** [comment]
Closing this as we believe it was resolved. Please re-open if still an issue
