### ISSUE TITLE
cannot request via ftp

### ISSUE THREAD

**Issue by L4H0** [drftpd-ng/drftpd#184]
I cannot request via ftp. irc request is working.

via ftp 530 access denied
drftpd 3.4.3 and flash or ftp rush
debian 9 64bit
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0+deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

even if i login as siteop, nothing works
perms.conf is written correctly, also request.conf.

is there anything do add in any config to solve the prob?

**Comment by hrxcodes** [comment]
Hi, the default only allows members of the `=request` to use `site request`.
You can try adding yourself to the group or modifying `conf/ftpcommands.conf` to allow the relevant groups.
