### ISSUE TITLE
first  Login failed

### ISSUE THREAD

**Issue by jbqi** [drftpd-ng/drftpd#185]
ftp 192.168.81.81 9982
Connected to 192.168.81.81 (192.168.81.81).
220 DrFTPD 3.4.3 https://github.com/drftpd-ng/drftpd3
Name (192.168.81.81:root): drftpd
530 Access denied
Login failed.

**Comment by 0xmarco** [comment]
First login should be done on the same machine you are running drftpd.

**Comment by jbqi** [comment]
> First login should be done on the same machine you are running drftpd.

I operated on the same machine

Any questions about using FTP to log in?

**Comment by mvangoor** [comment]
Hi @jbqi,

I think it was not very clear, but the default mask is "*@127.0.0.1".
So even if ip 192.168.81.81 is the ip of the host, you need to connect to 127.0.0.1

Good luck

**Comment by jbqi** [comment]
ftp 127.0.0.1 2121
Connected to 127.0.0.1 (127.0.0.1).
220 DrFTPD 3.4.3 https://github.com/drftpd-ng/drftpd3
Name (127.0.0.1:root): drftpd
530 USE SECURE CONNECTION
Login failed.
ftp> quit

perms.conf
userrejectinsecure      *   Modified to    userrejectinsecure      !*


open 127.0.0.1 2121
Connected to 127.0.0.1 (127.0.0.1).
220 DrFTPD 3.4.3 https://github.com/drftpd-ng/drftpd3
Name (127.0.0.1:root): drftpd
331 Password required for drftpd.
Password:
230- 
230-         Welcome to the future of FXP:ing
230-      ___      _____________  ___
230-     / _ \____/ __/_  __/ _ \/ _ \
230-    / // / __/ _/  / / / ___/ // /
230-   /____/_/ /_/   /_/ /_/  /____/
230-                   DistRibuted FTP Daemon
230-     https://github.com/drftpd-ng/drftpd3
230- 
230 user logged in successfully.

Thank you very much!

**Comment by Maverick1983** [comment]
Hi, this not update on repository. Need to update "perms.conf" file

**Comment by BakasuraRCE** [comment]
use lftp with option `set ssl:verify-certificate no` instead change perms.conf
