### ISSUE TITLE
Cannot run program "mediainfo": error=2, No such file or directory.

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#196]
**Describe the bug**
In admin chan: 
```
<slavename> went offline: java.io.IOException: Cannot run program "mediainfo": error=2, No such file or directory.
```

**To Reproduce**
Not sure, medinfo is enabled on master (which is itself a error) but this could be handled more gracefullty than killing the slave.

**Expected behavior**
Not crash if mediainfo binary is not found

**DrFTPD**
 - DrFTPD version: 4

**Comment by mvangoor** [comment]
This was fixed with commit 687d37c50cfdf3aee0631bb34d850e8411a23616

The slave fails to load if mediainfo is missing now
