### ISSUE TITLE
error on clean 4.0 install

### ISSUE THREAD

**Issue by L4H0** [drftpd-ng/drftpd#212]
mvn validate runs ok but when i mvn install get this error:

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project drftpd-common: Fatal error compiling: invalid flag: --release -> [Help 1]

can anybody help??

**Comment by zc0nf** [comment]
Hello,
You probably don't have the right version of java installed.
Version 4.0.0 requires 15, if you are using the latest commit you need to install 16.
Check your version using `java -version`

**Comment by zc0nf** [comment]
Please read the README and follow the java version needed depending on what you downloaded (stable or unstable)
