### ISSUE TITLE
Some find command options no longer work (mp3, flac, zipscript)

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#215]
**Describe the bug**
Some find command options no longer work (mp3, flac, zipscript)

**To Reproduce**
```
!find -mp3year 2021 -print
site find -mp3year 2021 -print
...

```
**Expected behavior**
The zipscript, mp3 and flac options should work.

**DrFTPD**
 - DrFTPD 4.0.0 / 4.0.1-git

**Additional context**
These commands worked in version 3.2.

**Comment by hrxcodes** [comment]
This is also confirmed true for `-endswith´ and `0byte`
