### ISSUE TITLE
Problem with the search command, the root path is not enforced during the search

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#220]
**Describe the bug**
Problem with the search command, the root path is not enforced during the search.

**To Reproduce**

```
<~xx> !raw SITE1 site search MY.GREAT.JOB
<+xx> 200- No results found!
<+xx> 200 Search complete
<+xx> Ok.
```

`DEBUG 2021-04-10T22:20:50,391 [FtpConn thread 53 servicing test/siteop] org.drftpd.master.network.BaseFtpConnection [] - << site search MY.GREAT.JOB`

```
<~xx> !raw SITE1 CWD /
<+slftp> 250 Directory changed to /
<+slftp> Ok.
<~xx> !raw SITE1 site search MY.GREAT.JOB
<+slftp> 200- Found 1 entries in index (limit 50):
<+slftp> 200- /FOLDER/MY.GREAT.JOB
<+slftp> 200 Search complete
<+slftp> Ok.
```

**Expected behavior**
The search command must search from the root path. The problem may also be occurring with other commands.

**DrFTPD**
 - DrFTPD 4.0.0/4.0.1-git

**FTP Client:**
 - FTP software: [SLFTP 1.5.7]

**Comment by hrxcodes** [comment]
Fixed in https://github.com/drftpd-ng/drftpd/commit/ff3117405e116e0e159829b73bc59590a2bccb81
