### ISSUE TITLE
Incomplete Catch : YOU'RE BEHIND A NAT ROUTER

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#227]
**Describe the bug**
Only network range A and C are catched.

**To Reproduce**

DataConnectionHandler.java

```
        if ((portHostAddress.startsWith("192.168.") &&
                !clientHostAddress.startsWith("192.168.")) ||
                (portHostAddress.startsWith("10.") &&
                        !clientHostAddress.startsWith("10."))) {
            CommandResponse response = new CommandResponse(501);
            response.addComment("==YOU'RE BEHIND A NAT ROUTER==");
            response.addComment(
                    "Configure the firewall settings of your FTP client");
            response.addComment("  to use your real IP: " +
                    conn.getControlSocket().getInetAddress().getHostAddress());
            response.addComment("And set up port forwarding in your router.");
            response.addComment(
                    "Or you can just use a PRET capable client, see");
            response.addComment("  https://github.com/drftpd-ng/drftpd/wiki for PRET capable clients");

            reset(conn);
            return response;
        }
```
**Expected behavior**
Complete RFC1918.
eg: [https://stackoverflow.com/questions/9729378/check-whether-the-ipaddress-is-in-private-range](https://stackoverflow.com/questions/9729378/check-whether-the-ipaddress-is-in-private-range)

**DrFTPD**
 - Java version [16.0.1]
 - DrFTPD version [4.0.1]

**Comment by hrxcodes** [comment]
The following would be reasonable to catch:

Private networks for internal use:
* 10.0.0.0/8
  * 10.0.0.0–10.255.255.255
* 172.16.0.0/12
  * 172.16.0.0–172.31.255.255
* 192.168.0.0/16
  * 192.168.0.0–192.168.255.255

Then if your slave is behind a Carrier-grade NAY (CGNAT / NAT444) we might want to warn about that too:
* 100.64.0.0/10
  * 100.64.0.0–100.127.255.255
