### ISSUE TITLE
Upload of Files with specific Patterns denied

### ISSUE THREAD

**Issue by daniel7152** [drftpd-ng/drftpd#230]
when uploading files, some are rejected with "530 Access denied". This happens when filename includes pattern like "(2)" or "(123)" anywhere in the filename

**To Reproduce**
1. Log on FTP
2. Upload or FXP a file with (2) in filename
3. Server denies upload

**Expected behavior**
it looks like this should avoid duplicated upload of files. clients like ftprush (when badly configured) do append "(2)" and so on when file already exists on server. Thus the feature on drftpd makes sense, but improved:
a) configurable
b) regex improved to it only matches at the end of filename: \(\d{1,3}\)\.....?$

**DrFTPD**
OS: Linux vers. 5.9.0-0.bpo.5-amd64 (amd64)
OS: Description: Debian GNU/Linux 10 (buster)
JVM: Java HotSpot(TM) 64-Bit Server VM vers. 16 by Oracle Corporation
DrFTPD 4.0.1-git

**FTP Client:**
- FTPRush, but doesnt matter

**additional info**

as zc0nf suggested in #drftpd we checked perms.conf and changed uploadex from default to uploadex \\p{javaWhitespace}+ !*
this didnt change behaviour as described above.

**Comment by hrxcodes** [comment]
This works in a clean build with default config, so your issue is likely in configuration.
Access denied might be upload perms to the folder etc.. but the file is allowed in default configuration.

**Comment by hrxcodes** [comment]
I'll go ahead and close this since we have not heard back from you and it works in the default configuration
