### ISSUE TITLE
Es werden keine incomplete links generiert

### ISSUE THREAD

**Issue by Bambam11699** [drftpd-ng/drftpd#234]
Es werden keine Incomplete links generiert wenn DIRs nicht vollständig sind

**Comment by mvangoor** [comment]
Hallo,

Kannst du deine config anlieveren?
Vielleicht log berichtte beim einladen?

**Comment by Bambam11699** [comment]
welche config genau ? zipscript ?

**Comment by mvangoor** [comment]
incomplete links ist eine function von linkmanager, nicht des zipscript.

Kannst du die konfiguration from linkmanager geben?

**Comment by Bambam11699** [comment]
1.type=LATESTDiR
1.dirname=/_LAST_RACES_
1.section=*
1.exclude=^/(.*)/(?i)(Sample|Subs|sample|subs)$
1.sectionexclude=^(?i)(PRE|SiTEOP|GROUPS)$
1.deleteon=*
1.linkname=(LAST RACES)-${dirname}
1.addparentdir=^(?i)(((cd|dvd|dis[ck])[1-9])|sample|subs|rarfix|Sample|Subs)$

2.type=SFVINCOMPLETE
2.dirname=/_iNCOMPLETES_
2.section=*
2.exclude=^/(.*)/(?i)(Sample|Subs|sample|subs)$
2.sectionexclude=^(?i)(PRE|SiTEOP|GROUPS)$
2.deleteon=*
2.linkname=(iNCOMPLETE)-${dirname}
2.addparentdir=^(?i)(((cd|dvd|dis[ck])[1-9])|sample|subs|rarfix|Sample|Subs)$

3.type=SFVINCOMPLETE 
3.dirname=%
3.section=*                                   
3.exclude=                                    
3.sectionexclude=^(?i)(pre|staff|speedtests)$ 
3.deleteon=*                                  
3.linkname=(incomplete)-${dirname}            
3.addparentdir=^/(.*)/((cd|dvd|dis[ck])[1-9])$
