### ISSUE TITLE
Update Readme for correct adding of a slave

### ISSUE THREAD

**Issue by d3vils** [drftpd-ng/drftpd#240]
Readme says to add a slave do "Execute remote commands: SITE ADD SLAVE SLAVENAME and SITE SLAVE SLAVENAME ADDMASK *@IP.MASK" There is no SITE ADD SLAVE command it is SITE ADDSLAVE

Readme should say "Execute remote commands: SITE ADDSLAVE SLAVENAME and SITE SLAVE SLAVENAME ADDMASK *@IP.MASK"

**Comment by zc0nf** [comment]
Fixed. Thx ;-)
