### ISSUE TITLE
SYSOP failed announces for PASS/IDNT/USER

### ISSUE THREAD

**Issue by schimschewski** [drftpd-ng/drftpd#242]
https://github.com/drftpd-ng/drftpd/blob/2503967dae1bc9acf3f93c03230ab3a8181bd52b/src/plugins/sitebot/src/main/java/org/drftpd/master/sitebot/plugins/sysop/SysopPostHook.java#L50

the 530 statement won't let the announcer work with PASS/IDNT/USER = 3, because a failed login will always be code 530

**Comment by mvangoor** [comment]
Checked the code and cannot find a logical reason why we have this hardcoded check for 530

**Comment by mvangoor** [comment]
Sorry for the delay on this one
