### ISSUE TITLE
Integers are not saved in the javabean file properly

### ISSUE THREAD

**Issue by schimschewski** [drftpd-ng/drftpd#243]
**Describe the bug**
Some integer data in the javabeans files are not stored properly. the value is "null".
it considers all keys in the "_data" field. Other integers work fine

**To Reproduce**
1. Log on FTP, 
2. create user
3. "site change USER ratio 5"
4. Restart Master
5. "site user USER" will show ratio 0.

**Expected behavior**
Javabean should save the integers properly.

**DrFTPD**
 - OS: Debian 11
 - DrFTPD version tested with 4.0.2 & 4.0.3

**FTP Client:**
 - OS: Windows 10
 - FTP software: FtpRush

`"@items":[
      {
        "@type":"date",
        "value":1630440683801
      },
      {
        "@type":"int",
        "value":null
      },
      {
        "@type":"int",
        "value":null
      },
      {
        "@type":"date",
        "value":1630440683801
      },
      {
        "@type":"date",
        "value":1630440683801
      },
      {
        "@type":"int",
        "value":null
      },
      "Added by siteop",
      "",
      {
        "@type":"float",
        "value":null
      },
      "No tagline set.",
      0,
      {
        "@type":"int",
        "value":null
      }
    ]`

**Comment by mvangoor** [comment]
The bug is in serialization of numeric types (integer, float, etc).
This seems related to JDK16 and/or json-io.
We have reverted drftpd back to jdk15 with https://github.com/drftpd-ng/drftpd/commit/052abca5ba0cde8824ce5478099202d80f2a6e92 which should (for now) solve this.

We are debating how best to move forward.
