### ISSUE TITLE
cbbncd bouncer

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#250]
**Describe the bug**
When setting up cbbncd in front of drftpd and trying to connect I see this log entry in drftpd logs:
```
==> master.log <==
INFO 2021-10-23T16:47:57,591 [Master Main Thread] org.drftpd.master.Master [] - Listening on port 2121
ERROR 2021-10-23T16:48:05,753 [FtpConnection Handler-59 - Waiting for connections] org.drftpd.master.network.BaseFtpConnection [] - HOSTMASKS is not set, this should not be possible... BUG
```

cbbncd logs:
```
[16:48:05] [192.168.100.5:36712] New client connection
[16:48:05] [192.168.100.5:36712] Connecting to server: 192.168.100.5:2121
[16:48:05] [192.168.100.5:36712] Server connection established.
[16:48:05] [192.168.100.5:36712] Sending: IDNT *@192.168.100.5:192.168.100.5
[16:48:05] [192.168.100.5:36712] Bouncing enabled.
```
Another users however mentions he has had cbbncd working from drftpd 4.0.2 - 4.0.6

**To Reproduce**
1. `wget https://cbftp.eu/cbbncd-0.16.tar.gz`
2. `tar xfz cbbncd-0.16.tar.gz && cd cbbncd-0.16`
3. `make`
4. Bind on a local IP, this will be the IP you add in `config/perms.conf` for `bouncer_ips`
5. Start cbbncd `./cbbncd`
6. Stat DR master
7. Try to connect via cbbncd port
8. Check error in drftpd logs

**Expected behavior**
A connection to happen via bouncer

**DrFTPD**
 - DrFTPD version: 4.0.7-git `0a99d1c989449c9a4c022b604b98311da1969e2b`

**FTP Client:**
 - FTP software: linux `ftp` command

**Comment by mvangoor** [comment]
This should now be correctly fixed
