### ISSUE TITLE
Slave goes offline if accidently try renaming a folder the same name

### ISSUE THREAD

**Issue by flasherss** [drftpd-ng/drftpd#254]
Happens when someone try's to rename a folder to the same name it already is

Slave.log below.

https://0bin.net/paste/JAJW4szS#4xw05wCDRKAUifmYN4YUOtCcnkRncWZWhR4Sap6-DhD

**Comment by mvangoor** [comment]
This is handled in the Dir.java file RNTO function.

There is a lot of logic here that needs to be followed in order to see what happens

https://github.com/drftpd-ng/drftpd/blob/master/src/core/master/src/main/java/org/drftpd/master/commands/dir/Dir.java#L358
