### ISSUE TITLE
Increase the usage of compound assignment operators

### ISSUE THREAD

**Issue by elfring** [drftpd-ng/drftpd#262]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of compound operators](https://docs.oracle.com/javase/specs/jls/se17/html/jls-15.html#jls-15.26 "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#\b(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-*/%^]|&(?!&)|\|(?!\|)|<<|>>>?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/DrFTPD/lokal -name '*.java')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 34 lines of this software?

**Comment by hrxcodes** [comment]
There are far more important things to do before this. I think you got some good replies in the other repos you created similar issues in.
If you want to run linting and PR fixes you are more than welcome to.
