### ISSUE TITLE
PRET command specifications

### ISSUE THREAD

**Issue by c0fe** [drftpd-ng/drftpd#263]
We need some documented specifications on the PRET command that are consistent and are published that can be implemented easily by FTP clients. I do not see any.

**Comment by hrxcodes** [comment]
* https://datatracker.ietf.org/doc/draft-dd-pret/
* https://www.ietf.org/archive/id/draft-dd-pret-00.txt

**Comment by mvangoor** [comment]
@c0fe the draft was never formalized by the IETF.

I do not know the reasons for that and this leads to a chicken/egg issue as ftp client writers have opinions about any non-standardized FTP commands versus adding support for something that's been around for over 15 years...

Not much we can do here unless someone actively pushes IETF to finish the draft
