### ISSUE TITLE
Slave terminates due to dependencies not being installed.

### ISSUE THREAD

**Issue by RolandRat42** [drftpd-ng/drftpd#266]
**Describe the bug**

***BUG***

DrFTPD Slave starting, further logging will be done through log4j

Exception in thread "FileLockThread" java.lang.NullPointerException: Cannot invoke "java.io.ObjectInputStream.available()" because "this.this$0._sin" is null at org.drftpd.slave.Slave$FileLockRunnable.run(Slave.java:693) 
 at Java.base/java.lang.Thread.run(Thread.java:832)

**To Reproduce**

Assume the following has been completed:

1. Installed Java JDK or OpenJDK 15, Apache Maven, Git on MASTER.
2. Installed Java SE or OpenJDK 15 on SLAVE.
3. mvn validate
4. mvn install
5. genkey.bat has generated a drftpd.key
6. Have a copy of drftpd.key within each of the config folders (master & slave parent folders have a config folder in each)
7. Run master.bat
8. Run slave.bat
9. This leads to the slave crashing out with an error.

**Expected behavior**
Master and slave start with errors. Allowing then, to execute remote commands such SITE ADDSLAVE SLAVENAME and SITE SLAVE SLAVENAME ADDMASK *@IP.MASK, for example/

**DrFTPD**
 - OS: Windows Server 2019 R2
 - Java version: JDK 15.0.2 (jdk-15.0.2_windows-x64_bin.exe)
 - DrFTPD version: 4.0.7

**FTP Client:**
 - OS: Windows 10 21H2
 - FTP software: FTPRush v1.1 and FlashFXP 5.4.0 Build 3970
 - Version: NA

**Additional context**

This occurs due to the following step not being completed:

Add needed deps that are not present:
MediaInfo (CLI): https://mediaarea.net/en/MediaInfo
mkvalidator tool: https://github.com/Matroska-Org/foundation-source

So to prevent this error, install MediaInfo from the link provided and copy the contents of the install folder into the root of the slave folder. (For example: C:\drftpd\runtime\slave\).

Note: Upon running slave.bat, a GUI window opens for MediaInfo. I may have the wrong installation. CLI is probably needed rather than the GUI.

Also, if your bug is related to a specific plugin, consider attaching your build.conf file.

**Comment by mvangoor** [comment]
This has been resolved in https://github.com/drftpd-ng/drftpd/commit/abfdd969d4726aa1468bd6572888ce26d1eb6f81

This will not stop the slave connecting to the master, but will fail protocol exchange if master expects mediainfo plugin to be available.

Slave will now also show errors if both binaries are missing
