### ISSUE TITLE
site addslave - Does not write slave json straight away

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#279]
**Describe the bug**
The writing is delayed, was able to write the file by issuing `site slave testslave addmask *@127.0.0.1`

**To Reproduce**
1. Log on FTP
2. `site addslave testslave`
3. `testslave.json` is absent in `userdata/slaves/`

**Expected behavior**
`testslave.json` is written as part of addslave process so that it can't exist in running config but not in persistent

**Comment by mike-codez** [comment]
Fixed with #288
