### ISSUE TITLE
site addgroup - Does not write slave json straight away

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#280]
**Describe the bug**
Similar to https://github.com/drftpd-ng/drftpd/issues/279 the file is not written, which means I could create the group but not delete it as the json was never written. 

**To Reproduce**
1. Log on FTP, or issue a IRC command
2. addgroup sometest
3. delgroup sometest
4. Fails to delete the group because json is not written but exists in runtime

**Expected behavior**
`addgroup` followed by `delgroup` should first write, then delete the file.

**Comment by mike-codez** [comment]
Fixed with #288
