### ISSUE TITLE
Migration to Maven

### ISSUE THREAD

**Issue by k-2-r** [drftpd-ng/drftpd#49]
Just an open discussion on the current plugin framework.

JPF is outdated, difficult to understand and need custom compilation. Migrating to OSGI (+maven) could be a valuable move.

**Comment by Scitz0** [comment]
Could be a move worth looking into but its a big change and requires more developers than are currently active on this project.

**Comment by k-2-r** [comment]
Yes its a huge work to do. Im just curious about what do you plan next ;)

**Comment by Scitz0** [comment]
I dont have a big plan except solving bugs at this point, no time for anything else and hardly this. But we welcome new developers to the project with good Java knowledge to drive it forward.

**Comment by k-2-r** [comment]
Sounds good ;)

**Comment by zc0nf** [comment]
Done
