### ISSUE TITLE
Many mods

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#65]
Hello,

Already exist for DR2 but its possible to implement? :

- fairness
[http://forums.drftpd.org/viewtopic.php?f=14&t=3162](http://forums.drftpd.org/viewtopic.php?f=14&t=2561)
- swho
[http://forums.drftpd.org/viewtopic.php?f=14&t=3162](http://forums.drftpd.org/viewtopic.php?f=14&t=3162)
- drbackup
{http://forums.drftpd.org/viewtopic.php?f=14&t=585](http://forums.drftpd.org/viewtopic.php?f=14&t=585)

- section rules

- Enhancement of find command :

Options : incomplete and nuked
Actions : wipe incomplete and nuked
[http://forums.drftpd.org/viewtopic.php?f=14&t=597](http://forums.drftpd.org/viewtopic.php?f=14&t=597)

- Enhancement of deny up_fxp and dn_fxp (show on irc when a user try to fxp)

Thx! :)

**Comment by bibidinu** [comment]
UP!

**Comment by bibidinu** [comment]
do you think they will ever be available? :D

**Comment by epochyx** [comment]
I don't know much about "fairness" or "drbackup" as the forum is down, but swho & site find -incomplete are implemented in 3.2.0 natively

**Comment by bibidinu** [comment]
@epochyx this dev dont have this mod

**Comment by epochyx** [comment]
not sure what you're talking about, but if you load the zipscript find module (org.drftpd.commands.find.zipscript) this is available on the master branch. swho is in org.drftpd.commands.usermanagement but I'm pretty sure this is loaded by default. You have to enable it in the ftp / irc command obviously, though the .dist conf files have them enabled it seems.

**Comment by zc0nf** [comment]
rules.properties 

`rules.head=${color}15${bold}RULES${coloroff}

rules.help=${color}15${bold}RULES${coloroff} -> These are the available sections:

rules.section=${color}15${bold}SECTIONS${coloroff} -> ${count}: ${color}4${bold}(${coloroff}${bold}${section}${color}4${bold}${bold})${coloroff}

rules.notsection=${color}15${bold}RULES${coloroff} -> Not a valide Section ...

rules.nofile=${color}15${bold}RULES${coloroff} -> No rules for this section,Have Fun ...`

rules.java

`package net.drmods.plugins.irc;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.StringTokenizer;


import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.HashMap;

import net.sf.drftpd.util.ReplacerUtils;

import org.apache.log4j.Logger;
import org.drftpd.GlobalContext;
import org.drftpd.plugins.SiteBot;
import org.drftpd.sections.SectionInterface;
import org.tanesha.replacer.ReplacerEnvironment;

import org.drftpd.sitebot.IRCCommand;
import f00f.net.irc.martyr.commands.MessageCommand;

/**
* @author NicoFr38
* @version $Id:$
*/

public class Rules extends IRCCommand {

        private static final Logger logger = Logger.getLogger(Rules.class);

        public Rules(GlobalContext gctx) {
                super(gctx);
        }

        public ArrayList<String> doRules(String args, MessageCommand msgc) {
                ArrayList<String> out = new ArrayList<String>();
                
                ReplacerEnvironment env = new ReplacerEnvironment(SiteBot.GLOBAL_ENV);
                
                out.add(ReplacerUtils.jprintf("rules.head", env, Rules.class));
                
                StringTokenizer st = new StringTokenizer(args);
                
                if (st.countTokens() != 1) {
                	out.add(ReplacerUtils.jprintf("rules.help", env, Rules.class));
                	
                	int i = 1;
                  /* Loop through all the sections */
                  for (SectionInterface section :  getGlobalContext().getSectionManager().getSections()) {
                        env.add("count", i++);
                        env.add("section", section.getName());
                        out.add(ReplacerUtils.jprintf("rules.section", env, Rules.class));
                  }
                  return out;
                }
                else {
                	String strSection = st.nextToken();
                	String strOKSection = "";
                	for (SectionInterface section :  getGlobalContext().getSectionManager().getSections()) {
                		if (section.getName().equals(strSection)){
                			strOKSection = "OK";
                		}
                	}
                	if (strOKSection != "OK") {
                		out.add(ReplacerUtils.jprintf("rules.notsection", env, Rules.class));
                		out.add(ReplacerUtils.jprintf("rules.help", env, Rules.class));
                	
                		int i = 1;
	                  /* Loop through all the sections */
	                  for (SectionInterface section :  getGlobalContext().getSectionManager().getSections()) {
	                        env.add("count", i++);
	                        env.add("section", section.getName());
	                        out.add(ReplacerUtils.jprintf("rules.section", env, Rules.class));
	                  }
	                  return out;
                	}
                	else {
                		try {
                				String strFileSection = "text/rules/"+strSection+".txt";
		                    BufferedReader rd = new BufferedReader(new InputStreamReader(
		                            new FileInputStream((String) strFileSection), "ISO-8859-1"));
		                    String line;
		
		                    try {
		                        while ((line = rd.readLine()) != null) {
		                            out.add(line);
		                        }
		                    } finally {
		                        rd.close();
		                    }
		                } catch (UnsupportedEncodingException e) {
		                    logger.warn(e);
		                } catch (FileNotFoundException e) {
		                    logger.warn(e);
		                    out.add(ReplacerUtils.jprintf("rules.nofile", env, Rules.class));
		                } catch (IOException e) {
		                    logger.warn(e);
		                }
		                return out;
                	}
                }
        }
}
`

**Comment by k-2-r** [comment]
Need to be split in several tickets.

**Comment by zc0nf** [comment]
https://github.com/drftpd-ng/drftpd/issues/139

**Comment by zc0nf** [comment]
https://github.com/drftpd-ng/drftpd/issues/140

**Comment by zc0nf** [comment]
https://github.com/drftpd-ng/drftpd/issues/141
