### ISSUE TITLE
userdata folder not created for slaves when unzipping slave.zip

### ISSUE THREAD

**Issue by d3vils** [drftpd-ng/drftpd#79]
The userdata folder is missing from slave.zip when unzipping from the slave.zip.
This folder needs created in order to put the key file in it if you wish to have slaves use SSL to connect to master in the develop branch currently

**Comment by zc0nf** [comment]
Not fixed, revert...

**Comment by zc0nf** [comment]
the userdata directory is no longer needed in the 4.x branch, this problem will not be fixed in the 3.x branch
