### ISSUE TITLE
How to kill ghost connections

### ISSUE THREAD

**Issue by donmagic1** [drftpd-ng/drftpd#80]
on previouse dr there were command !username it kills ghost connections, its missing says no such user when you add !

**Comment by donmagic1** [comment]
[09:42:31] [L] site who
[09:42:31] [L] 200- <new>       -> Idle for 3d 23h
[09:42:31] [L] 200- <new>       -> Idle for 3d 23h
[09:42:31] [L] 200- <new>       -> Idle for 3d 23h
[09:42:31] [L] 200- <new>       -> Idle for 3d 23h
[09:42:31] [L] 200- <new>       -> Idle for 3d 13h
[09:42:31] [L] 200- <new>       -> Idle for 3d  9h
[09:42:31] [L] 200- <new>       -> Idle for 3d  5h
[09:42:31] [L] 200- <new>       -> Idle for 2d 23h
[09:42:31] [L] 200- <new>       -> Idle for 2d 18h
[09:42:31] [L] 200- <new>       -> Idle for 2d 11h
[09:42:31] [L] 200- <new>       -> Idle for 2d 11h
[09:42:31] [L] 200- <new>       -> Idle for 1d 20h
[09:42:31] [L] 200- <new>       -> Idle for 1d 18h
[09:42:31] [L] 200- <new>       -> Idle for 1d  0h

 could it lead to portbouncer not closing connection?

**Comment by epochyx** [comment]
Hi,
What did the command do exactly? Also dr 3.x needs an actual static command name as it is, but it could be !kick or !ghost, I'm just not clear what you want it to do.

**Comment by zc0nf** [comment]
From drftpd2 svn1057 : 

`Index: trunk/src/net/sf/drftpd/master/command/plugins/Login.java
===================================================================
--- trunk/src/net/sf/drftpd/master/command/plugins/Login.java	(revision 1057)
+++ trunk/src/net/sf/drftpd/master/command/plugins/Login.java	(working copy)
@@ -43,6 +43,8 @@
 
 import java.net.InetAddress;
 import java.net.UnknownHostException;
+import java.util.ArrayList;
+import java.util.Iterator;
 
 /**
  * @author mog
@@ -56,6 +58,7 @@
      */
     protected InetAddress _idntAddress;
     protected String _idntIdent;
+    protected boolean _killghosts = false;
 
     /**
      * Syntax: IDNT ident@ip:dns
@@ -133,7 +136,25 @@
                 logger.warn("Error reading welcome", e);
             }
 
-            return response;
+        	if (_killghosts) {
+        		// basically cut & paste from UserManagement.doSITE_KICK()
+                ArrayList<BaseFtpConnection> conns = new ArrayList<BaseFtpConnection>(conn.getGlobalContext()
+                									.getConnectionManager()
+                									.getConnections());
+                for (Iterator iter = conns.iterator(); iter.hasNext();) {
+                	BaseFtpConnection conn2 = (BaseFtpConnection) iter.next();
+                	try {
+                    	if (conn2 != conn && conn2.getUser() == conn.getUser() && 
+                    			(System.currentTimeMillis() - conn2.getLastActive()) / 1000 > 30) {
+                        	conn2.stop("Self kicked by ! prefix.");
+                    	}
+                	} catch (NoSuchUserException e) {
+                		// gracefully ignored
+                	}
+            	}
+        	}
+
+        	return response;
         }
 
         return new Reply(530, conn.jprintf(Login.class, "pass.fail"));
@@ -171,9 +192,17 @@
         }
 
         User newUser;
+        String username;
+        if ( request.getArgument().startsWith("!")) {
+    		username = request.getArgument().substring(1).trim();
+    		_killghosts = true;
+        } else {
+    		username = request.getArgument().trim();
+    		_killghosts = false;
+        }
 
         try {
-            newUser = conn.getGlobalContext().getUserManager().getUserByNameIncludeDeleted(request.getArgument());
+            newUser = conn.getGlobalContext().getUserManager().getUserByNameIncludeDeleted(username);
         } catch (NoSuchUserException ex) {
             return new Reply(530, ex.getMessage());
         } catch (UserFileException ex) {
`

**Comment by zc0nf** [comment]
@epochyx 
https://0bin.net/paste/QHjLwt3pncDV7VKK#OPNk1GPL9vH51oj3FUNNfO7nMgKosxz1Fa1GYteD6iw

**Comment by zc0nf** [comment]
https://github.com/drftpd-ng/drftpd/issues/142
